#pragma once

#include <vector>
#include <string>

enum SCRIPT_TYPE
{
	ARROWSKILL,
	ATTACKSTATE,
	BACKSCRIPT,
	BELLUMATTACKSTATE,
	BELLUMIDLESTATE,
	BELLUMSCRIPT,
	BOWSKILL,
	CAMERASCRIPT,
	DAMAGESKINSCRIPT,
	DIESTATE,
	DOUBLEJUMPSKILL,
	HEROAURABLADESKILL,
	HEROCOMBOATTACKSKILL,
	HEROFLASHSLASHSKILL,
	HERORAGINGBLOWSKILL,
	HEROSLASHBLASTSKILL,
	HEROSOBSSTATE_ATTACK,
	HEROSOBSSTATE_DIE,
	HEROSOBSSTATE_IDLE,
	HEROSOBSSTATE_REGEN,
	HEROSWORDOFBURNINGSOULSCRIPT,
	HEROSWORDOFBURNINGSOULSKILL,
	HEROWARLEAPSKILL,
	HITSTATE,
	IDLESTATE,
	LEVELSCRIPT,
	LIFESCRIPT,
	LINEPLATFORM,
	LINEWALL,
	LUCIDDRAGONSCRIPT,
	LUCIDDRAGONSKILL,
	LUCIDDRAGONSTATE_ATTACK,
	LUCIDDRAGONSTATE_MOVE,
	LUCIDEXPLOSIONPRISONSKILL,
	LUCIDFAIRYDUSTSKILL,
	LUCIDFLOWEREXPLOSIONSCRIPT,
	LUCIDGOLEMSCRIPT,
	LUCIDGOLEMSTATE_DROP,
	LUCIDGOLEMSTATE_SPAWN,
	LUCIDHORNSCRIPT,
	LUCIDLITTLEBUTTERFLYBOMBSCRIPT,
	LUCIDLITTLEBUTTERFLYSCRIPT,
	LUCIDLITTLEBUTTERFLYSPAWNSCRIPT,
	LUCIDNIGHTMAREBUTTERFLYSCRIPT,
	LUCIDNIGHTMAREBUTTERFLYSTATE_ATTACK,
	LUCIDNIGHTMAREBUTTERFLYSTATE_DIE,
	LUCIDNIGHTMAREBUTTERFLYSTATE_FLY,
	LUCIDNIGHTMAREBUTTERFLYSTATE_HIT,
	LUCIDNIGHTMAREBUTTERFLYSTATE_REGEN,
	LUCIDPHASE1SCRIPT,
	LUCIDPHASE2SCRIPT,
	LUCIDPRISONSTATE_DIE,
	LUCIDPRISONSTATE_REGEN,
	LUCIDPRISONSTATE_STAY,
	LUCIDSCRIPT,
	LUCIDTOADSTOOLSCRIPT,
	MISSILESCRIPT,
	MONSTERSCRIPT,
	MOUSESCRIPT,
	MULTIPLAYERSCRIPT,
	PARTICLESYSTEMSCRIPT,
	PATROLSTATE,
	PLATFORMERSCRIPT,
	PLATFORMSCRIPT,
	PLAYERATTACKSTATE,
	PLAYERIDLESTATE,
	PLAYERSCRIPT,
	PORTALSCRIPT,
	PROJECTILESCRIPT,
	ROPE,
	SKILLMANAGER,
	SKILLSCRIPT,
	SKILLSTATE,
	SPAWNERSCRIPT,
	SPAWNSTATE,
	STRIKESKILL,
	TRACESTATE,
	WALLSCRIPT,
	WINDWALKSKILL,
};

using namespace std;

class CScript;

class CScriptMgr
{
public:
	static void GetScriptInfo(vector<wstring>& _vec);
	static CScript * GetScript(const wstring& _strScriptName);
	static CScript * GetScript(UINT _iScriptType);
	static const wchar_t * GetScriptName(CScript * _pScript);
};
